// Literals are as discovered in WN-LMF-1.3.dtd.
//
// Note: wordnet_types.ts is not necessarily lists all of these

export const PartsOfSpeech = {
  n: "Noun",
  v: "Verb",
  a: "Adjective",
  r: "Adverb",
  s: "Adjective Satellite",
  t: "?",
  c: "Conjunction",
  p: "Adposition (Preposition, postposition, etc.)",
  x: "Other (inc. particle, classifier, bound morphemes, determiners)",
  u: "Unknown",
};

export const SenseRelationRelType = {
  also: "",
  anto_converse: "",
  anto_gradable: "",
  anto_simple: "",
  antonym: "",
  augmentative: "",
  derivation: "",
  diminutive: "",
  domain_region: "",
  domain_topic: "",
  exemplifies: "",
  feminine: "",
  has_augmentative: "",
  has_diminutive: "",
  has_domain_region: "",
  has_domain_topic: "",
  has_feminine: "",
  has_masculine: "",
  has_young: "",
  is_exemplified_by: "",
  masculine: "",
  other: "",
  participle: "",
  pertainym: "",
  secondary_aspect_ip: "",
  secondary_aspect_pi: "",
  similar: "",
  simple_aspect_ip: "",
  simple_aspect_pi: "",
  young: "",
};

export const SynsetRelationRelType = {
  agent: "",
  also: "",
  anto_converse: "",
  anto_gradable: "",
  anto_simple: "",
  antonym: "",
  attribute: "",
  augmentative: "",
  be_in_state: "",
  causes: "",
  classified_by: "",
  classifies: "",
  co_agent_instrument: "",
  co_agent_patient: "",
  co_agent_result: "",
  co_instrument_agent: "",
  co_instrument_patient: "",
  co_instrument_result: "",
  co_patient_agent: "",
  co_patient_instrument: "",
  co_result_agent: "",
  co_result_instrument: "",
  co_role: "",
  diminutive: "",
  direction: "",
  domain_region: "",
  domain_topic: "",
  entails: "",
  eq_synonym: "",
  exemplifies: "",
  feminine: "",
  has_augmentative: "",
  has_diminutive: "",
  has_domain_region: "",
  has_domain_topic: "",
  has_feminine: "",
  has_masculine: "",
  has_young: "",
  holo_location: "",
  holo_member: "",
  holo_part: "",
  holo_portion: "",
  holo_substance: "",
  holonym: "",
  hypernym: "",
  hyponym: "",
  in_manner: "",
  instance_hypernym: "",
  instance_hyponym: "",
  instrument: "",
  involved: "",
  involved_agent: "",
  involved_direction: "",
  involved_instrument: "",
  involved_location: "",
  involved_patient: "",
  involved_result: "",
  involved_source_direction: "",
  involved_target_direction: "",
  ir_synonym: "",
  is_caused_by: "",
  is_entailed_by: "",
  is_exemplified_by: "",
  is_subevent_of: "",
  location: "",
  manner_of: "",
  masculine: "",
  mero_location: "",
  mero_member: "",
  mero_part: "",
  mero_portion: "",
  mero_substance: "",
  meronym: "",
  other: "",
  patient: "",
  restricted_by: "",
  restricts: "",
  result: "",
  role: "",
  similar: "",
  source_direction: "",
  state_of: "",
  subevent: "",
  target_direction: "",
  young: "",
};

export const AdjPosition = {
  a: "",
  ip: "",
  p: "",
};
